# Site settings
title: Design and code
email: post@jelmerdemaat.nl
description: ""
baseurl: ""
url: "http://jelmerdemaat.nl"
exclude: [
	"Gruntfile.js",
	"*.sublime-*",
	"node_modules",
	"package.json",
	"sass",
	"jsraw"
	]
destination: "./dist"
plugins: "./_plugins"


# Build settings
markdown: kramdown
permalink: /:year/:title/