# Site settings
title: Design and code
email: post@jelmerdemaat.nl
description: ""
baseurl: "http://192.168.0.108:3000"
url: "http://jelmerdemaat.nl"
exclude: [
		"Gruntfile.js",
		"*.sublime-*",
		"node_modules",
		"package.json",
		"sass",
		"jsraw"
	]
destination: "./dist"
plugins: "./_plugins"


# Build settings
markdown: kramdown
permalink: /:year/:title/